### ISSUE TITLE
Enable dynamic Identifiers

### ISSUE THREAD

**Issue by ozten** [mozilla/id-specs#18]
Currently, the Persona login screen and BrowserID protocol assumes the user will authenticate an identity which is exactly the one which they have typed in to the 'Email' field.

We want to make dynamic identifiers (and thus Identities) possible.

Use Cases:
- Opaque Identifiers - Our BlueVia IdP will not have any user input and will generate an opaque id for each user
- Pseudonymity - An IdP that with a stable user ID which authenticates as other pseudonyms.
- Spam avoidance - alice+SpamFromExampleCom@gmail.com

Proposed changes to the spec:

Update beginAuthentication to indicate that `email` is a hint and not a hard requirement. Email may actually be null.
It's up to the IdP's discretion on how to authenticate the user as controlling an identity or identities. 

```
navigator.id.beginAuthentication(function(email) {
       // email may be null
       // but lets assume email is alice@example.com
});
```

Update completeAuthentication to take a dictionary with `id` as the actual identifier chosen for the current user.

Also, an IdP can indicate that certain dynamic identities shouldn't show up in the email picker.

```
navigator.id.completeAuthentication({
        “id”: "bob@example.com"
});
```

If the dynamic identifier (bob@example.com in this case) is not SMTP routable, it should indicate this in the certificate it issues to the user.

```
{
  “principal”: {“email”: “...”, “protocol”: null}
}
```

An RP can request an identity from an IdP by using `requireDomain` instead of the more specific `requireEmail` in `navigator.id.request` or `navigator.id.watch`.

**Comment by ozten** [comment]
@benadida questions:

1) Does navigator.id.completeAuthentication inform the UI picker? If not, why does it exist?

2) navigator.id.registerCertificate **must** be called with a cert where the principal is the dynamic id (which was used with completeAuthentication) right? Wouldn't this be sufficient, why completeAuthentication too?

3) For the use case where no existing IdP session, I think the first call to `beginProvisioning` is the stable email which the user typed into the dialog, but the second call to `beginProvisioning` matches the dynamic id registered during authentication, right?

4) For the use case where the user has an active IdP session, should `beginProvisioning` be the stable email which the user just typed in or their previously used dynamic id?

**Comment by benadida** [comment]
1) yes, completeAuthentication would have to inform the picker.

2) I don't want to do this via registerCertificate, because _provisioning_ might need a true prescription for the email being provisioned, in case the user is logged in as two users. So, the dynamic ID should be obtained in the auth phase, and then provision provisions the email it's told.

3) and 4) It's not really dependent on whether there's an IdP session. The normal flow means there will always be a provision flow first. What matters is that, if we switch the authentication flow to be specified as receiving a _hint_ rather than a _prescription_ for the email address, then we allow for  (a) recovering from google account confusion, (b) pseudonyms!!, and (c) account setup flow for Firefox OS. In (c), you would expect that we go immediately to authenticate flow, no first provision flow.

4)

**Comment by ozten** [comment]
Won't fix.
