### ISSUE TITLE
Single-address delegation

### ISSUE THREAD

**Issue by djc** [mozilla/id-specs#31]
It seems like this scenario isn't supported right now: say my email address foo@example.com in fact forwards to foo.bar@gmail.com. It would be great if I can setup a support document on example.com to make the IdP for gmail.com (in this case, BigTent?) handle identification for foo@example.com.

IIRC this is something that works with OpenID.

**Comment by fmarier** [comment]
This works when you're delegating to a domain with native support.

As for the bridge, we can't do that because we have locked the bridge down to `gmail.com` and `googlemail.com` addresses. The reason for these restrictions is that we ran into alias problems when we tried to support Google Apps For Your Domain.

**Comment by djc** [comment]
@fmarier, sorry, not sure I understand you. If there's redirection at my native IdP, I don't think there's a need for support at the redirected-to IdP? At least that's the kind of redirection I was going for.

**Comment by fmarier** [comment]
Oh, i completely missed the title of this bug :)

We do have support for dynamic support documents (which I believe is what makes `http://persowna.net` work) but I'm not sure it fully satisfies your requirement.

**Comment by djc** [comment]
Yeah, I think that doesn't support the issue outlined in my original post.
